name: CI Checks
env:
  bashPass:   \033[32;1mPASSED -
  bashInfo:   \033[33;1mINFO -
  bashFail:   \033[31;1mFAILED -
  bashEnd:    \033[0m

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - env:
          stepName: Install Dependencies
        working-directory: cdk
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"

          sudo apt install npm nodejs -y;
          sudo npm install -g aws-cdk aws-cdk-lib;
          npm install;

          echo -e "::endgroup::"
          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"

      - env:
          stepName: Build CDK Package
        shell: bash
        working-directory: cdk
        run: |
          # ${{ env.stepName }}
          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"

          # Set values in config-params.ts to perform the build
          sed -i "s/endpoint: \"\"/endpoint: \"BUILD_ENDPOINT\"/g" config-params.ts;
          sed -i "s/thingName: \"\"/thingName: \"BUILD_THING_NAME\"/g" config-params.ts;
          sed -i "s/email: ''/email: 'BUILD_EMAIL'/g" config-params.ts;

          # Bootstrap the CDK, then perform a build
          cdk bootstrap;
          cdk build;

          echo -e "::endgroup::"
          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run spellings check
        uses: FreeRTOS/CI-CD-Github-Actions/spellings@main

  link-verifier:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3

      - name: Link Verification
        uses: FreeRTOS/CI-CD-Github-Actions/link-verifier@main

  formatting:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3

      - name: Check Formatting
        uses: FreeRTOS/CI-CD-Github-Actions/formatting@main
